// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANgXRlQrqF9lpEJG_bThgqbasRBMHcIhc',
    appId: '1:1078270406715:web:293739dd871b4ce7446c1e',
    messagingSenderId: '1078270406715',
    projectId: 'cajero-automatico-fd89b',
    authDomain: 'cajero-automatico-fd89b.firebaseapp.com',
    storageBucket: 'cajero-automatico-fd89b.firebasestorage.app',
    measurementId: 'G-YGCJB57RFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTJG8ZrHF85Le20P3Onwub0mtmLaC5nSw',
    appId: '1:1078270406715:android:a50412f187fdfb4c446c1e',
    messagingSenderId: '1078270406715',
    projectId: 'cajero-automatico-fd89b',
    storageBucket: 'cajero-automatico-fd89b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9ki1dN61GOmj49Z7OBz6rFvZi0Sh_clw',
    appId: '1:1078270406715:ios:20e9e5ec5919a897446c1e',
    messagingSenderId: '1078270406715',
    projectId: 'cajero-automatico-fd89b',
    storageBucket: 'cajero-automatico-fd89b.firebasestorage.app',
    iosBundleId: 'com.example.cajeroAutomatico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9ki1dN61GOmj49Z7OBz6rFvZi0Sh_clw',
    appId: '1:1078270406715:ios:20e9e5ec5919a897446c1e',
    messagingSenderId: '1078270406715',
    projectId: 'cajero-automatico-fd89b',
    storageBucket: 'cajero-automatico-fd89b.firebasestorage.app',
    iosBundleId: 'com.example.cajeroAutomatico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANgXRlQrqF9lpEJG_bThgqbasRBMHcIhc',
    appId: '1:1078270406715:web:87b3dae6c728314b446c1e',
    messagingSenderId: '1078270406715',
    projectId: 'cajero-automatico-fd89b',
    authDomain: 'cajero-automatico-fd89b.firebaseapp.com',
    storageBucket: 'cajero-automatico-fd89b.firebasestorage.app',
    measurementId: 'G-TEHQ37NN0J',
  );
}
